version: '3.9'

services:
  postgres:
    image: mcr.microsoft.com/mssql/server:${TAG}
    ports:
      - 5434:1433
    volumes:
      - volum-db:/var/opt/mssql
    environment:
      - SA_PASSWORDD=${PASSWORD}
      - ACCEPT_EULA=Y
volumes:
  volum-db: